AMENITIES = ['Wifi',
             'Smoke alarm',
             'Essentials',
             'Heating',
             'Air conditioning',
             'Kitchen',
             'Hangers',
             'TV',
             'Iron',
             'Washer',
             'Dryer',
             'Shampoo',
             'Carbon monoxide alarm',
             'Hair dryer',
             'Laptop-friendly workspace',
             'Hot water',
             'Fire extinguisher',
             'Refrigerator',
             'Microwave',
             'Dishes and silverware',
             'Coffee maker',
             'Private entrance',
             'Oven',
             'Stove',
             'Bed linens',
             'Cooking basics',
             'First aid kit',
             'Free street parking',
             'Dishwasher',
             'Extra pillows and blankets',
             'Long term stays allowed',
             'Cable TV',
             'Free parking on premises',
             'Patio or balcony',
             'Luggage dropoff allowed',
             'Lockbox',
             'Garden or backyard',
             'Keypad',
             'Elevator',
             'Gym',
             'Lock on bedroom door',
             'Bathtub',
             'BBQ grill',
             'Indoor fireplace',
             'Breakfast',
             'Shower gel',
             'Paid parking on premises',
             'Paid parking off premises',
             'Pool',
             'Pack \'n Play/travel crib']
